### ISSUE TITLE
Conflict on buildout

### ISSUE THREAD

**Issue by taschini** [morepath/reg#26]
Following the instructions in ``developing.rst``, I get the following error on running ``./bin/buildout``:

```
Error: There is a version conflict.
We already have: pyflakes 1.1.0
but flake8 2.5.4 requires 'pyflakes<1.1,>=0.8.1'.

```

**Comment by faassen** [comment]
I've run into this recently in various buildouts, I fixed it by removing the pyflakes dependency and relying on flake8. It's because flake8 wants an older version of pyflakes. I'll fix this now.

**Comment by taschini** [comment]
Thank you.
