### ISSUE TITLE
``inspect.getargspec`` is deprecated in Python 3.5

### ISSUE THREAD

**Issue by taschini** [morepath/reg#34]
Python 3.5 deprecates `inspect.getargspec` in favor of `inspect.signature`. It is used by the `arginfo` function in the `reg.arginfo` module.

**Comment by faassen** [comment]
Thanks for pointing this out! Supporting that is going to complicated arginfo even more, as it's already juggling differences between python 2, python 3 and pypy.

**Comment by nandoflorestan** [comment]
I believe this is now causing Reg to throw on Python 3.6 if we use type annotations on the Regged function. Compatibility with type annotations would be extremely welcome.

By the way, thanks for creating Reg, it is awesome!!1

**Comment by faassen** [comment]
Could you create a small failing test case and post this and the traceback you get?

**Comment by nandoflorestan** [comment]
Sure. Here is a Python module that will fail to import in 3.6:

    """Reg throws on Python 3.6 when the function has type annotations."""

    from typing import Any, Dict
    import reg


    @reg.dispatch(  # Dispatch on type of *obj* and value of *flavor*.
        reg.match_instance('obj'),
        reg.match_key('flavor', lambda obj, flavor, **kw: flavor))
    # Cannot type-annotate this function, Reg 0.11 does not support it
    def to_dict(obj: Any, flavor: str='default', **kw) -> Dict:
        return {}

    '''I am using Reg in order to build a general to_dict() component at
    https://github.com/nandoflorestan/kerno/blob/master/kerno/web/json.py

    It works if I remove the type annotations. Otherwise:

    Traceback (most recent call last):
      File "./reg_fails.py", line 11, in <module>
        def to_dict(obj: Any, flavor: str='default', **kw) -> Dict:
      File "/home/nando/.virtualenvs/36/lib/python3.6/site-packages/reg-0.11-py3.6.egg/reg/dispatch.py", line 44, in __call__
        return Dispatch(self.predicates, callable, self.get_key_lookup).call
      File "/home/nando/.virtualenvs/36/lib/python3.6/site-packages/reg-0.11-py3.6.egg/reg/dispatch.py", line 101, in __init__
        self._define_call()
      File "/home/nando/.virtualenvs/36/lib/python3.6/site-packages/reg-0.11-py3.6.egg/reg/dispatch.py", line 132, in _define_call
        args = arginfo(self.wrapped_func)
      File "/home/nando/.virtualenvs/36/lib/python3.6/site-packages/reg-0.11-py3.6.egg/reg/arginfo.py", line 36, in arginfo
        result = inspect.getargspec(func)
      File "/usr/lib/python3.6/inspect.py", line 1072, in getargspec
        raise ValueError("Function has keyword-only parameters or annotations"
    ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
    '''

**Comment by henri-hulski** [comment]
Fixed in c114fbb.

**Comment by nandoflorestan** [comment]
Awesome, thanks.  I would welcome a release with the fix.

**Comment by henri-hulski** [comment]
I just wait for the review of the Black integration and if @faassen is agree make releases after.
