### ISSUE TITLE
fastmapply

### ISSUE THREAD

**Issue by faassen** [morepath/reg#41]
There's an implementation on a branch that reimplements mapply (and arginfo) in C for performance (and invisibility from debugging). We should merge this at some point.

**Comment by taschini** [comment]
Is ``mapply`` still present in critical paths performance-wise?

**Comment by faassen** [comment]
It's not in the dispatch logic at all anymore, so it's much less performance critical than before. (its performance impact wasn't as great as I'd hoped anyway). It's used in ``publish.consume`` in Morepath so it used at least once per request, in mounted apps, more often.

One side effect of the C implementation is that debuggers also don't go through it anymore -- it's really not code that you want to see over and over in a debugger.

**Comment by taschini** [comment]
So, as far as I understand, ``mapply`` is not used by Reg nor by Dectate, only by Morepath. So perhaps it should be moved to Morepath?

Once it is an internal object of Morepath, it is also probably easier to refactor and optimise it, as we no longer have any concern on the API stability of Reg.

**Comment by faassen** [comment]
Yes, that's a good idea; it's possible Morepath can implement something more efficient during configuration time eventually.

Concerning fastmapply, there's fancy code in it that lets you deal with function arguments in C, which is actually also needed for an implementation for bits of argextract in C. I'm looking into that now so I'm recycling a lot of the code and knowledge.

**Comment by taschini** [comment]
The PR morepath/morepath#491 has removed ``mapply`` from the critical path in Morepath too.

I think we can close this issue now.

**Comment by faassen** [comment]
You're right. Closing.
