### ISSUE TITLE
decoupling-fastargextract branch

### ISSUE THREAD

**Issue by faassen** [morepath/reg#43]
This branch contains a C implementation of the ArgExtractor logic.

While the performance impact on a simple benchmark with Morepath is minimal, the dispatch performance has gone up quite a bit compared to the plain decoupling branch.

The decoupling branch does this when you execute ``speed.py``:

```
dispatch 0 args
2.50691318512
dispatch 1 args
4.27959012985
dispatch 2 args
6.44276189804
dispatch 3 args
7.31519389153
dispatch 4 args
8.34504699707
Plain func 0 args
0.161817789078
Plain func 4 args
0.481851100922
```

while the fastargextract branch does this:

```
dispatch 0 args
2.0502038002
dispatch 1 args
2.98760485649
dispatch 2 args
4.65890598297
dispatch 3 args
5.31285595894
dispatch 4 args
5.77068710327
Plain func 0 args
0.161151885986
Plain func 4 args
0.491057157516
```

So that shaves off quite a bit of time from dispatch performance, even though it's nowhere near plain function call performance.

**Comment by taschini** [comment]
In a5cbba84ceb4aaa3bb30d628ffcec2159df01945 I removed ArgExtractor from the critical path, so a C optimisation is no longer needed.

Since ``perf.py`` outputs naked timings, it does not make any sense for me to post here the benchmark output, as we have two different machines.  Anyway, you should see a sensible improvement over the C implementation.

**Comment by faassen** [comment]
Cool, better to do away with this altogether. I'm closing this issue.

**Comment by faassen** [comment]
For posterity here the benchmarks on my machine with @taschini 's changes:

```
dispatch 0 args
1.25924301147
dispatch 1 args
2.03821897507
dispatch 2 args
3.58315300941
dispatch 3 args
4.08871388435
dispatch 4 args
4.67021179199
Plain func 0 args
0.159023046494
Plain func 4 args
0.48424077034
```

Faster than C. :)
