### ISSUE TITLE
invocation hook

### ISSUE THREAD

**Issue by faassen** [morepath/reg#44]
@taschini wrote:

  I would like to have an invocation hook as an argument to ``dispatch_method``. This hook is a callable
  that is passed on to the ``DispatchMethodDescriptor`` like ``get_key_lookup`` and that is invoked on
  obj when the ``DispatchMethodDescriptor.__get__`` is invoked:

  ```
  class DispatchMethodDescriptor(object):
     ...
     def __get__(self, obj, type=None):
         self.invocation_hook(obj)
         ...
   ```
  If cache_bound_method is true, than the hook is executed only once.

Could you go into the use case for this, @taschini?

**Comment by taschini** [comment]
The idea would be to use the hook to carry out some pre-invocation checks (perhaps ``preinvocation_hook`` is a better name) before the method is invoked the first time.

In the case of Morepath, to make sure that the app is committed.  If you forget to commit the app you get no error, simply you always get the fallback behaviour.

**Comment by taschini** [comment]
An even better name would be perhaps ``first_invocation_hook``.
