### ISSUE TITLE
making register a decorator

### ISSUE THREAD

**Issue by faassen** [morepath/reg#47]
Currently ``register`` works like this::

```
def implementation(a):
    ...

foo.register(implementation, a=A)
```

So the implementation registered is the first argument. I propose we change ``register`` so it can
be used as a decorator:

```
@foo.register(a=A)
def implementation(a):
    ...
```

``register`` returns a function that does the real registration when called. In Morepath we'd not really benefit, we'd have to rewrite:

```
app_class.foo.register(obj, **predicates)
```

into:

```
app_class.foo.register(**predicates)(obj)
```

but that's doable enough, and it does make Reg's api by itself cleaner.

**Comment by taschini** [comment]
If you want to keep backward compatibility it  is also possible to do it as follows:

```python
def register(self, func=None, **key_dict):
    if func is None:
         return partial(self.register, **key_dict)
    validate_signature(func, self.wrapped_func)
    predicate_key = self.registry.key_dict_to_predicate_key(key_dict)
    self.register_value(predicate_key, func)
```

In this way you can use it as a decorator or programmatically as it is done in Morepath without any changes.

**Comment by faassen** [comment]
After some thinking about it, that looks good. We should implement it with some tests before we release this version of Reg. We should also update the documentation to make use of decorators where appropriate, and indicate that you can do this in the API docs.

**Comment by taschini** [comment]
In the commit here above I implemented the proposal, added a few tests, updated the docstring and update the narrative docs in [``usage.rst``](http://taschini-reg.readthedocs.io/en/latest/usage.html).

I also took this opportunity to add a section on dispatched methods in [``usage.rst``](http://taschini-reg.readthedocs.io/en/latest/usage.html#dispatch-methods), including a sidebar on the different between ``Dispatch.register`` and ``Dispatch.register_function``.

Feel free to edit the docs as you please.

**Comment by taschini** [comment]
On the other hand, I just realised that ``Dispatch.register_function`` is in fact redundant, as it really is just equivalent to ``Dispatch.register`` + ``methodify``, so we'd be probably better off removing it from the API.

**Comment by faassen** [comment]
Since this is working now, closing this issue.
