### ISSUE TITLE
The value attribute of methodified functions

### ISSUE THREAD

**Issue by taschini** [morepath/reg#49]
Methodified functions (i.e., functions wrapped by ``methodify``, ``methodify_auto``, ``DispatchMethod.register_function``, ``DispatchMethod.register_auto``) provide a way to retrieve the original function.

This is currently done via a ``value`` attribute, which is problematic for two reasons:

1. ``methodify_auto`` must wrap functions that wouldn't need it just to be able to set the ``value`` attribute.

2. ``DispatchMethod.register_auto`` attaches the ``value`` attribute directly to the callable passed as an argument, which might lead to unexpected behaviour if the callable already has a value attribute.

My suggestion is to introduce a separate function, tentatively called ``inspect_methodified``. In principle, it would behave something like the following (implementation details can be ironed out later on):

```python
def inspect_methodified(func):
    return getattr(func, 'value', func)
```

It will return ``func.value`` if the attribute exists, i.e., if the function has been wrapped, and will return ``func`` if it has not been wrapped.

In this way, no unnecessary wrapping is done and no potential bugs are introduced.

**Comment by faassen** [comment]
I'm +1 on this, though I'd call it: ``get_registered_function`` or ``get_unwrapped_function`` or possibly just ``unwrap``.

**Comment by faassen** [comment]
Given the discussion in #50 I think it might me correct to call it ``reg.unmethodify``, as it inverses the operation of ``methodify``.

**Comment by faassen** [comment]
I created an ``unmethodify`` but I realized Morepath actually doesn't use this feature anymore. So now I'm wondering whether to take it all out. Your opinion?

**Comment by taschini** [comment]
I would take it out too (actually, move it to ``reg/tests/test_dispatch_method.py``)

**Comment by faassen** [comment]
Okay, I did what you suggested and moved it into the tests.

**Comment by taschini** [comment]
Thank you!
