### ISSUE TITLE
inspect.getargspec() is deprecated

### ISSUE THREAD

**Issue by kagesenshi** [morepath/reg#55]
Getting this deprecation warning from python3.6:

`/home/izhar/.local/share/virtualenvs/morpfw-fr-Ugi9v/lib/python3.6/site-packages/reg/arginfo.py:36: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
`

**Comment by RonnyPfannschmidt** [comment]
@faassen i believe a port to funcsigs2/funcsigs might help to sort this out once and for all, its a bit of work to ensure it works proper however

**Comment by fmarczin** [comment]
Has there been any further progress or a decision about how to proceed?

**Comment by RonnyPfannschmidt** [comment]
no

**Comment by faassen** [comment]
We'd be happy to see a PR for this. It is rather tricky to make it work on Python 2, Python 3 AND pypy and I don't think I'm quite ready to give up on Python 2 yet. What we could do is detect Python 3 and shunt into an entirely different code path if we see it.

**Comment by href** [comment]
Given that Python 2.7 is going to be dead in less than a year and that 3.8 will no longer support `inspect.getargspec()` I would actually suggest we drop Python 2.7 by the time 3.8 rolls around.

I suspect that by January 2020 it will get harder and harder to maintain backwards compatibility as a lot of packages will drop Python 2.7 support as well.

**Comment by bwo** [comment]
this actively breaks if you're using `__annotations__` under python3.7.

**Comment by nandoflorestan** [comment]
+1 for dropping support for Python 2.7.  By the way, this issue is generating hundreds of repeat warnings in my application tests and making development a bit... uncomfortable.  This should be a priority.

**Comment by RonnyPfannschmidt** [comment]
i'll take a look at porting to signature

**Comment by nandoflorestan** [comment]
@RonnyPfannschmidt when you say "signature" do you mean
https://github.com/keleshev/signature
...a project that hasn't seen a commit in 7 years???

Removing the warnings is super easy by using `result = inspect.getfullargspec(func)` and a couple more lines changed -- but I think this is not a good solution, a good solution will allow usage of typing annotations on the decorated functions.

In any case I don't understand why we'd need to use any external library.

**Comment by RonnyPfannschmidt** [comment]
@nandoflorestan inspect.signature/funcsigs2

**Comment by nandoflorestan** [comment]
@RonnyPfannschmidt here's a commit that gets rid of the warnings:

https://github.com/nandoflorestan/reg/commit/864d529ec509466899edc1665b43b172e5dd22f7

Problem is, this creates a lot more to do:

- Decorated functions still cannot have typing annotations.
- Documentation still mentions "getargspec".
- Python 2.7 probably no longer works, so support for it should be dropped.

**Comment by nandoflorestan** [comment]
It would be great if @faassen gave us permission to drop Python 2.7 support now.

The warnings are just a symptom that this library is getting stuck in the past.  But the fact that decorated functions break reg if they have typing annotations is a more serious symptom.

Python 2.7 will always be able to use the current version of reg.  But we need to move forward...

**Comment by henri-hulski** [comment]
I also run into the same issue.
@faassen I really think it's time to drop Python 2.7.

**Comment by faassen** [comment]
Let's go ahead and drop the Python 2 support then. I think this library doesn't have a lot Python 2 users.

Let's just make sure we continue to cache things because last I checked getting this information was somewhat te consuming

I am looking forward to a PR!

**Comment by henri-hulski** [comment]
Not sure how to fix the reg issue, but I can look into the cleaning up morepath and Reg etc from Python 2 code.

**Comment by nandoflorestan** [comment]
Thanks guys!  Now @RonnyPfannschmidt you said "i'll take a look at porting to signature", didn't you?  It should be easier now  :D

**Comment by faassen** [comment]
@henri-hulski happy to see those cleanup PRs too.

**Comment by RonnyPfannschmidt** [comment]
im working on it, there is a few details which are a pain (part of not knowing the codebase)

**Comment by RonnyPfannschmidt** [comment]
i dont have enough time to make signatures work today, so its likely best to start off by integrating @nandoflorestan 's work as it kills the warning, even tho annotations are not yet taken into account

**Comment by henri-hulski** [comment]
Ok I've created PRs to remove Python 2 from morepath. reg, dectate and importscan.
You're welcome to review!

**Comment by henri-hulski** [comment]
@RonnyPfannschmidt  We still need the fix for arginfo signatures.

**Comment by henri-hulski** [comment]
@nandoflorestan @RonnyPfannschmidt @faassen   I have fixed the issue in c114fbb by replacing inspect.getargspec() by inspect.getfullargspec().
As inspect.getfullargspec() isn't deprecated anymore this should work fine.
We should add some tests for annotations, but normally they should work now.
