### ISSUE TITLE
Update supported Python versions

### ISSUE THREAD

**Issue by jugmac00** [morepath/reg#61]
- drop support for Python versions < 3.6
- add support for Python versions 3.7, 3.8 (if missing)
- fix linting errors (if present)

If you are a beginner, and need to help for this issue, especially during Hacktoberfest, please comment here or reach out to me via https://jugmac00.github.io/

**Comment by sgaist** [comment]
Hi,

I am interested into doing this one.

**Comment by jugmac00** [comment]
Go for it!
